// Lightweight instrument registry — metadata for every instrument, plus a
// lazy loader for its full scene/behavior. The metadata below (id through
// video) is duplicated from each module file's own default export — kept in
// sync automatically by scripts/smoke.mjs, which loads every module for real
// and fails the build if a field here doesn't match. Order shapes the
// workshop grid: grouped roughly by subject, easy → advanced.
export const REGISTRY = [
  {
    id: "pendulum",
    name: "Pendulum",
    tag: "Physics · Mechanics",
    subject: "Physics",
    grades: [7, 11],
    blurb: "Swing a bob and read its rhythm.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M20 5v6\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/><circle cx=\"20\" cy=\"11\" r=\"2.2\" fill=\"currentColor\"/><path d=\"M20 11L29 30\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/><circle cx=\"29\" cy=\"33\" r=\"4.2\" stroke=\"currentColor\" stroke-width=\"2\"/></svg>",
    video: { id: "WPa5IgLgDyQ", title: "Pendulums (Khan Academy)" },
    load: () => import("./pendulum.js"),
  },
  {
    id: "projectile",
    name: "Projectile range",
    tag: "Physics · Kinematics",
    subject: "Physics",
    grades: [9, 11],
    blurb: "Fire a cannon and chase the 45° sweet spot.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M6 32C14 12 26 8 34 8\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-dasharray=\"1 3\"/><circle cx=\"34\" cy=\"8\" r=\"3\" fill=\"currentColor\"/><path d=\"M4 33h10l-4-6\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linejoin=\"round\"/></svg>",
    load: () => import("./projectile.js"),
  },
  {
    id: "spring",
    name: "Mass on a spring",
    tag: "Physics · Oscillation",
    subject: "Physics",
    grades: [9, 11],
    blurb: "Hooke's law and simple harmonic motion.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M20 4v4M20 8c-6 0-6 4 0 4s6 4 0 4-6 4 0 4-6 4 0 4v4\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/><rect x=\"15\" y=\"30\" width=\"10\" height=\"7\" rx=\"1.5\" fill=\"currentColor\"/></svg>",
    load: () => import("./spring.js"),
  },
  {
    id: "incline",
    name: "Ramp & friction",
    tag: "Physics · Forces",
    subject: "Physics",
    grades: [9, 12],
    blurb: "Tilt the ramp until the block gives way.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M5 32h30L5 14z\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linejoin=\"round\"/><rect x=\"16\" y=\"16\" width=\"7\" height=\"7\" rx=\"1\" fill=\"currentColor\" transform=\"rotate(-31 19.5 19.5)\"/></svg>",
    load: () => import("./incline.js"),
  },
  {
    id: "cradle",
    name: "Newton's cradle",
    tag: "Physics · Momentum",
    subject: "Physics",
    grades: [9, 11],
    blurb: "Lift two, two swing out — every time.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M8 8h24M12 8l-4 16M20 8v16M28 8v16M12 8v16\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/><circle cx=\"8\" cy=\"26\" r=\"3\" fill=\"currentColor\"/><circle cx=\"20\" cy=\"26\" r=\"3\" fill=\"currentColor\"/><circle cx=\"28\" cy=\"26\" r=\"3\" fill=\"currentColor\"/></svg>",
    load: () => import("./cradle.js"),
  },
  {
    id: "levers",
    name: "Levers & balance",
    tag: "Physics · Simple machines",
    subject: "Physics",
    grades: [5, 9],
    blurb: "Move the fulcrum, lift more with less.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M6 16l28 6\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/><path d=\"M20 22l-3 8h6z\" fill=\"currentColor\"/><rect x=\"4\" y=\"12\" width=\"5\" height=\"5\" fill=\"currentColor\"/><rect x=\"31\" y=\"19\" width=\"4\" height=\"4\" fill=\"currentColor\"/></svg>",
    load: () => import("./levers.js"),
  },
  {
    id: "circuit",
    name: "Ohm's law loop",
    tag: "Physics · Electricity",
    subject: "Physics",
    grades: [7, 10],
    blurb: "Turn the dials, watch the current and the glow.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"7\" y=\"9\" width=\"26\" height=\"22\" rx=\"3\" stroke=\"currentColor\" stroke-width=\"2\"/><circle cx=\"20\" cy=\"9\" r=\"3.4\" fill=\"currentColor\"/><path d=\"M13 31v3M27 31v3\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/></svg>",
    video: { id: "F_vLWkkOETI", title: "Introduction to circuits and Ohm's law (Khan Academy)" },
    load: () => import("./circuit.js"),
  },
  {
    id: "resistors",
    name: "Series & parallel",
    tag: "Physics · Circuits",
    subject: "Physics",
    grades: [9, 12],
    blurb: "Two resistors, two ways to wire them.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M4 14h6l3-4 4 8 4-8 3 4h8M4 26h6l3-4 4 8 4-8 3 4h8\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>",
    load: () => import("./resistors.js"),
  },
  {
    id: "magnet",
    name: "Magnetic field",
    tag: "Physics · Magnetism",
    subject: "Physics",
    grades: [7, 12],
    blurb: "Field lines, and poles that pull or push.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M12 8v14a8 8 0 0 0 16 0V8M12 8h6M22 8h6M12 15h6M22 15h6\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/></svg>",
    load: () => import("./magnet.js"),
  },
  {
    id: "electromagnet",
    name: "Electromagnet",
    tag: "Physics · Electromagnetism",
    subject: "Physics",
    grades: [8, 12],
    blurb: "Current through a coil makes a magnet you can switch off.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M6 20h4M30 20h4M11 12c-4 0-4 16 0 16M15 12c-4 0-4 16 0 16M19 12c-4 0-4 16 0 16M23 12c-4 0-4 16 0 16\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/></svg>",
    load: () => import("./electromagnet.js"),
  },
  {
    id: "coulomb",
    name: "Electric charges",
    tag: "Physics · Electrostatics",
    subject: "Physics",
    grades: [9, 12],
    blurb: "Like repels, unlike attracts — Coulomb's law.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"11\" cy=\"20\" r=\"6\" stroke=\"currentColor\" stroke-width=\"2\"/><circle cx=\"29\" cy=\"20\" r=\"6\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M8 20h6M26 20h6M29 17v6\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/></svg>",
    load: () => import("./coulomb.js"),
  },
  {
    id: "waves",
    name: "Wave interference",
    tag: "Physics · Waves",
    subject: "Physics",
    grades: [9, 12],
    blurb: "Two ripple sources, one interference pattern.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M4 20c4-8 8-8 12 0s8 8 12 0 8-8 8 0\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/><path d=\"M4 28c4-8 8-8 12 0s8 8 12 0 8-8 8 0\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" opacity=\"0.5\"/></svg>",
    load: () => import("./waves.js"),
  },
  {
    id: "standing",
    name: "Standing waves",
    tag: "Physics · Waves & music",
    subject: "Physics",
    grades: [9, 12],
    blurb: "Pluck a string into its harmonics.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M5 20c5-12 10-12 15 0s10 12 15 0\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/><circle cx=\"5\" cy=\"20\" r=\"2.4\" fill=\"currentColor\"/><circle cx=\"35\" cy=\"20\" r=\"2.4\" fill=\"currentColor\"/></svg>",
    load: () => import("./standing.js"),
  },
  {
    id: "sound",
    name: "Sound: pitch & loudness",
    tag: "Physics · Sound",
    subject: "Physics",
    grades: [6, 10],
    blurb: "Frequency is pitch, amplitude is loudness.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M6 16v8h6l8 7V9l-8 7Z\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M27 14a10 10 0 0 1 0 12M31 10a15 15 0 0 1 0 20\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/></svg>",
    load: () => import("./sound.js"),
  },
  {
    id: "lens",
    name: "Converging lens",
    tag: "Physics · Optics",
    subject: "Physics",
    grades: [8, 12],
    blurb: "Slide the object and find where the image lands.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M20 6c5 6 5 22 0 28-5-6-5-22 0-28Z\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M4 20h32\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-dasharray=\"2 3\"/></svg>",
    load: () => import("./lens.js"),
  },
  {
    id: "refraction",
    name: "Refraction",
    tag: "Physics · Optics",
    subject: "Physics",
    grades: [9, 12],
    blurb: "Light bends where it crosses into water or glass.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M4 20h32\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-dasharray=\"2 3\"/><path d=\"M12 6l8 14\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M20 20l6 14\" stroke=\"currentColor\" stroke-width=\"2\"/></svg>",
    load: () => import("./refraction.js"),
  },
  {
    id: "buoyancy",
    name: "Float or sink",
    tag: "Physics · Fluids",
    subject: "Physics",
    grades: [6, 10],
    blurb: "Density decides — dial it up and down.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M5 22c4 3 6 3 10 0s6-3 10 0 6 3 10 0\" stroke=\"currentColor\" stroke-width=\"2\"/><rect x=\"15\" y=\"12\" width=\"10\" height=\"10\" fill=\"currentColor\"/></svg>",
    load: () => import("./buoyancy.js"),
  },
  {
    id: "heat",
    name: "Heat flow",
    tag: "Physics · Thermal",
    subject: "Physics",
    grades: [7, 11],
    blurb: "Touch a hot block to a cold one — watch them meet.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"6\" y=\"12\" width=\"12\" height=\"16\" rx=\"1.5\" stroke=\"currentColor\" stroke-width=\"2\"/><rect x=\"22\" y=\"12\" width=\"12\" height=\"16\" rx=\"1.5\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M18 20h4\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/></svg>",
    load: () => import("./heat.js"),
  },
  {
    id: "molecule",
    name: "Molecule kit",
    tag: "Chemistry · Bonding",
    subject: "Chemistry",
    grades: [9, 12],
    blurb: "Rotate real molecules and read their bond angles.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"20\" cy=\"14\" r=\"4.4\" fill=\"currentColor\"/><circle cx=\"12\" cy=\"28\" r=\"3.4\" stroke=\"currentColor\" stroke-width=\"2\"/><circle cx=\"28\" cy=\"28\" r=\"3.4\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M17.4 17.4L14 25M22.6 17.4L26 25\" stroke=\"currentColor\" stroke-width=\"2\"/></svg>",
    load: () => import("./molecule.js"),
  },
  {
    id: "states",
    name: "States of matter",
    tag: "Chemistry · Particles",
    subject: "Chemistry",
    grades: [5, 9],
    blurb: "Heat the box — solid, liquid, gas.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"7\" y=\"7\" width=\"26\" height=\"26\" rx=\"2\" stroke=\"currentColor\" stroke-width=\"2\"/><circle cx=\"14\" cy=\"14\" r=\"2\" fill=\"currentColor\"/><circle cx=\"21\" cy=\"15\" r=\"2\" fill=\"currentColor\"/><circle cx=\"27\" cy=\"13\" r=\"2\" fill=\"currentColor\"/><circle cx=\"15\" cy=\"24\" r=\"2\" fill=\"currentColor\"/><circle cx=\"24\" cy=\"26\" r=\"2\" fill=\"currentColor\"/></svg>",
    video: { id: "We7Kd4D0S90", title: "States of matter (Khan Academy)" },
    load: () => import("./states.js"),
  },
  {
    id: "atom",
    name: "Atom builder",
    tag: "Chemistry · Atomic structure",
    subject: "Chemistry",
    grades: [8, 11],
    blurb: "Add protons and electrons, name the element.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"20\" cy=\"20\" r=\"3\" fill=\"currentColor\"/><ellipse cx=\"20\" cy=\"20\" rx=\"15\" ry=\"6\" stroke=\"currentColor\" stroke-width=\"2\"/><ellipse cx=\"20\" cy=\"20\" rx=\"15\" ry=\"6\" stroke=\"currentColor\" stroke-width=\"2\" transform=\"rotate(60 20 20)\"/><ellipse cx=\"20\" cy=\"20\" rx=\"15\" ry=\"6\" stroke=\"currentColor\" stroke-width=\"2\" transform=\"rotate(120 20 20)\"/></svg>",
    load: () => import("./atom.js"),
  },
  {
    id: "gaslaws",
    name: "Gas laws",
    tag: "Chemistry · Gases",
    subject: "Chemistry",
    grades: [8, 12],
    blurb: "Squeeze it, heat it, read the pressure.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"12\" y=\"6\" width=\"16\" height=\"6\" rx=\"1\" fill=\"currentColor\"/><path d=\"M20 12v4M13 16h14v18H13z\" stroke=\"currentColor\" stroke-width=\"2\"/><circle cx=\"18\" cy=\"24\" r=\"1.5\" fill=\"currentColor\"/><circle cx=\"23\" cy=\"28\" r=\"1.5\" fill=\"currentColor\"/></svg>",
    load: () => import("./gaslaws.js"),
  },
  {
    id: "ph",
    name: "The pH scale",
    tag: "Chemistry · Acids & bases",
    subject: "Chemistry",
    grades: [7, 12],
    blurb: "Slide from lemon juice to drain cleaner.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M14 6h12M16 6v10L9 30a3 3 0 0 0 3 4h16a3 3 0 0 0 3-4l-7-14V6\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M12 24h16\" stroke=\"currentColor\" stroke-width=\"2\"/></svg>",
    load: () => import("./ph.js"),
  },
  {
    id: "reactionrate",
    name: "Reaction rate",
    tag: "Chemistry · Kinetics",
    subject: "Chemistry",
    grades: [9, 12],
    blurb: "Heat it, crowd it, add a catalyst — speed it up.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"13\" cy=\"14\" r=\"4\" fill=\"currentColor\"/><circle cx=\"26\" cy=\"17\" r=\"4\" stroke=\"currentColor\" stroke-width=\"2\"/><circle cx=\"16\" cy=\"27\" r=\"4\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M17 16l7 0M15 18l0 6\" stroke=\"currentColor\" stroke-width=\"1.6\"/></svg>",
    load: () => import("./reactionrate.js"),
  },
  {
    id: "balancing",
    name: "Balancing equations",
    tag: "Chemistry · Reactions",
    subject: "Chemistry",
    grades: [8, 10],
    blurb: "Same atoms in as out — find the coefficients.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"10\" cy=\"14\" r=\"4\" fill=\"currentColor\"/><circle cx=\"10\" cy=\"26\" r=\"4\" fill=\"currentColor\"/><path d=\"M18 20h14M28 20l-4-4M28 20l-4 4\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/></svg>",
    load: () => import("./balancing.js"),
  },
  {
    id: "periodic",
    name: "Periodic table",
    tag: "Chemistry · Elements",
    subject: "Chemistry",
    grades: [7, 12],
    blurb: "All 118 elements — orbit the wall, tap one.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"5\" y=\"7\" width=\"8\" height=\"8\" rx=\"1.5\" stroke=\"currentColor\" stroke-width=\"2\"/><rect x=\"27\" y=\"7\" width=\"8\" height=\"8\" rx=\"1.5\" stroke=\"currentColor\" stroke-width=\"2\"/><rect x=\"5\" y=\"19\" width=\"30\" height=\"8\" rx=\"1.5\" stroke=\"currentColor\" stroke-width=\"2\"/><rect x=\"9\" y=\"31\" width=\"22\" height=\"5\" rx=\"1.5\" stroke=\"currentColor\" stroke-width=\"2\"/></svg>",
    video: { id: "CtTmUlp3bBo", title: "The periodic table (Khan Academy)" },
    load: () => import("./periodic.js"),
  },
  {
    id: "cell",
    name: "Cell explorer",
    tag: "Biology · The cell",
    subject: "Biology",
    grades: [6, 10],
    blurb: "Fly inside a cell and tap its parts.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"20\" cy=\"20\" r=\"15\" stroke=\"currentColor\" stroke-width=\"2\"/><circle cx=\"22\" cy=\"18\" r=\"5\" fill=\"currentColor\"/><ellipse cx=\"13\" cy=\"25\" rx=\"4\" ry=\"2.4\" stroke=\"currentColor\" stroke-width=\"2\"/></svg>",
    load: () => import("./cell.js"),
  },
  {
    id: "dna",
    name: "DNA double helix",
    tag: "Biology · Genetics",
    subject: "Biology",
    grades: [9, 12],
    blurb: "Twist the ladder, watch A pair with T.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M14 6c0 8 12 8 12 16s-12 8-12 16M26 6c0 8-12 8-12 16s12 8 12 16\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/><path d=\"M15 13h10M15 27h10\" stroke=\"currentColor\" stroke-width=\"2\"/></svg>",
    video: { id: "34Jr2U7KwOE", title: "DNA structure and replication (Khan Academy)" },
    load: () => import("./dna.js"),
  },
  {
    id: "photosynthesis",
    name: "Photosynthesis",
    tag: "Biology · Plants",
    subject: "Biology",
    grades: [6, 11],
    blurb: "Light + CO₂ + water → sugar + oxygen.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M20 34c0-10 3-18 12-22-2 12-6 18-12 22ZM20 34c0-8-3-14-10-17 1 10 4 14 10 17Z\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linejoin=\"round\"/></svg>",
    video: { id: "sQK3Yr4Sc_k", title: "Photosynthesis: Crash Course Biology #8" },
    load: () => import("./photosynthesis.js"),
  },
  {
    id: "heart",
    name: "The heart",
    tag: "Biology · Circulation",
    subject: "Biology",
    grades: [6, 11],
    blurb: "Two loops, one pump, blue to red and back.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M20 33S6 24 6 15a7 7 0 0 1 14-3 7 7 0 0 1 14 3c0 9-14 18-14 18Z\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linejoin=\"round\"/></svg>",
    load: () => import("./heart.js"),
  },
  {
    id: "respiratory",
    name: "The respiratory system",
    tag: "Biology · Breathing",
    subject: "Biology",
    grades: [5, 9],
    blurb: "Watch the lungs and diaphragm move as the model breathes.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"20\" cy=\"8\" r=\"3\" fill=\"currentColor\"/><path d=\"M20 11v9\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M20 20c-8 0-11 5-11 12a4 4 0 0 0 8 0M20 20c8 0 11 5 11 12a4 4 0 0 1-8 0\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/></svg>",
    load: () => import("./respiratory.js"),
  },
  {
    id: "foodchain",
    name: "Energy pyramid",
    tag: "Biology · Ecosystems",
    subject: "Biology",
    grades: [6, 10],
    blurb: "Only 10% of energy passes up each level.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M20 6l14 28H6Z\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M11 24h18M14.5 17h11\" stroke=\"currentColor\" stroke-width=\"1.6\"/></svg>",
    load: () => import("./foodchain.js"),
  },
  {
    id: "genetics",
    name: "Punnett square",
    tag: "Biology · Genetics",
    subject: "Biology",
    grades: [9, 12],
    blurb: "Cross two parents, predict the offspring.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"7\" y=\"7\" width=\"26\" height=\"26\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M20 7v26M7 20h26\" stroke=\"currentColor\" stroke-width=\"2\"/></svg>",
    load: () => import("./genetics.js"),
  },
  {
    id: "plantparts",
    name: "Parts of a plant",
    tag: "Biology · Plants",
    subject: "Biology",
    grades: [2, 6],
    blurb: "Roots, stem, leaves, flower — what each part does for the plant.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M20 34V16\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/><path d=\"M20 20c-5 0-8-3-8-8 5 0 8 3 8 8ZM20 24c5 0 8-3 8-8-5 0-8 3-8 8Z\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linejoin=\"round\"/><circle cx=\"20\" cy=\"10\" r=\"4\" stroke=\"currentColor\" stroke-width=\"2\"/></svg>",
    load: () => import("./plantparts.js"),
  },
  {
    id: "solids",
    name: "Geometry set",
    tag: "Math · Solids",
    subject: "Math",
    grades: [5, 9],
    blurb: "Count faces, edges and corners on real 3D solids.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M20 6L33 14V28L20 36L7 28V14L20 6Z\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M20 6V20M20 20L33 14M20 20L7 14M20 20V36\" stroke=\"currentColor\" stroke-width=\"1.4\" opacity=\"0.6\"/></svg>",
    load: () => import("./solids.js"),
  },
  {
    id: "counting",
    name: "Counting blocks",
    tag: "Math · Numbers",
    subject: "Math",
    grades: [1, 3],
    blurb: "Count blocks one by one and watch tens and ones build up.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"6\" y=\"22\" width=\"8\" height=\"8\" rx=\"1\" stroke=\"currentColor\" stroke-width=\"2\"/><rect x=\"16\" y=\"22\" width=\"8\" height=\"8\" rx=\"1\" stroke=\"currentColor\" stroke-width=\"2\"/><rect x=\"16\" y=\"12\" width=\"8\" height=\"8\" rx=\"1\" stroke=\"currentColor\" stroke-width=\"2\"/><rect x=\"26\" y=\"22\" width=\"8\" height=\"8\" rx=\"1\" stroke=\"currentColor\" stroke-width=\"2\"/></svg>",
    load: () => import("./counting.js"),
  },
  {
    id: "shapes3d",
    name: "3D shapes explorer",
    tag: "Math · Shapes",
    subject: "Math",
    grades: [1, 4],
    blurb: "Cubes, spheres, cones and more — count their faces, edges and corners.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M8 14l12-6 12 6-12 6-12-6Z\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M8 14v12l12 6 12-6V14\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M20 20v12\" stroke=\"currentColor\" stroke-width=\"2\"/></svg>",
    load: () => import("./shapes3d.js"),
  },
  {
    id: "grapher",
    name: "Surface studio",
    tag: "Math · Functions",
    subject: "Math",
    grades: [10, 12],
    blurb: "Type any z = f(x, y) and walk around it.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M6 28c6 0 6-14 14-14s8 12 14 12\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/><path d=\"M6 34h28M8 34V12\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" opacity=\"0.6\"/></svg>",
    load: () => import("./grapher.js"),
  },
  {
    id: "fractions",
    name: "Fraction wall",
    tag: "Math · Fractions",
    subject: "Math",
    grades: [3, 6],
    blurb: "See which fraction is bigger.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"5\" y=\"9\" width=\"30\" height=\"6\" stroke=\"currentColor\" stroke-width=\"2\"/><rect x=\"5\" y=\"18\" width=\"30\" height=\"6\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M20 18v6M12.5 18v6M27.5 18v6\" stroke=\"currentColor\" stroke-width=\"2\"/><rect x=\"5\" y=\"27\" width=\"30\" height=\"6\" stroke=\"currentColor\" stroke-width=\"2\"/></svg>",
    load: () => import("./fractions.js"),
  },
  {
    id: "times",
    name: "Times table",
    tag: "Math · Multiplication",
    subject: "Math",
    grades: [2, 5],
    blurb: "Tap a square, see the product light up.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"6\" y=\"6\" width=\"28\" height=\"28\" rx=\"2\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M6 15h28M6 24h28M15 6v28M24 6v28\" stroke=\"currentColor\" stroke-width=\"1.6\" opacity=\"0.7\"/></svg>",
    load: () => import("./times.js"),
  },
  {
    id: "unitcircle",
    name: "Unit circle",
    tag: "Math · Trigonometry",
    subject: "Math",
    grades: [10, 12],
    blurb: "Spin the radius — read sin, cos, tan.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"20\" cy=\"20\" r=\"13\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M20 20l11-6M6 20h28M20 6v28\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/></svg>",
    video: { id: "1m9p9iubMLU", title: "Introduction to the unit circle (Khan Academy)" },
    load: () => import("./unitcircle.js"),
  },
  {
    id: "pythagoras",
    name: "Pythagoras",
    tag: "Math · Geometry",
    subject: "Math",
    grades: [7, 10],
    blurb: "a² + b² = c², drawn as real squares.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M10 30V12h18Z\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M10 30H4v6h6zM10 12v-6H4v6z\" stroke=\"currentColor\" stroke-width=\"1.6\"/></svg>",
    video: { id: "AA6RfgP-AHU", title: "The Pythagorean theorem, intro (Khan Academy)" },
    load: () => import("./pythagoras.js"),
  },
  {
    id: "similarity",
    name: "Similar triangles",
    tag: "Math · Geometry",
    subject: "Math",
    grades: [8, 10],
    blurb: "Same shape, different size — sides scale, area scales faster.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M6 30L12 14l10 16Z\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M16 34L26 8l16 26Z\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linejoin=\"round\"/></svg>",
    load: () => import("./similarity.js"),
  },
  {
    id: "linegraph",
    name: "Line grapher",
    tag: "Math · Coordinate geometry",
    subject: "Math",
    grades: [8, 11],
    blurb: "y = mx + c — slope and intercept, live.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M4 36h32M4 4v32\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M8 30L32 8\" stroke=\"currentColor\" stroke-width=\"2\"/></svg>",
    load: () => import("./linegraph.js"),
  },
  {
    id: "statistics",
    name: "Mean, median, mode",
    tag: "Math · Statistics",
    subject: "Math",
    grades: [6, 10],
    blurb: "Three ways to find the 'middle' — and when they disagree.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"6\" y=\"22\" width=\"5\" height=\"12\" fill=\"currentColor\"/><rect x=\"14\" y=\"14\" width=\"5\" height=\"20\" fill=\"currentColor\"/><rect x=\"22\" y=\"8\" width=\"5\" height=\"26\" fill=\"currentColor\"/><rect x=\"30\" y=\"18\" width=\"5\" height=\"16\" fill=\"currentColor\"/></svg>",
    video: { id: "h8EYEJ32oQ8", title: "Mean, median and mode, intro (Khan Academy)" },
    load: () => import("./statistics.js"),
  },
  {
    id: "galton",
    name: "Galton board",
    tag: "Math · Probability",
    subject: "Math",
    grades: [8, 12],
    blurb: "Drop beads, build a bell curve.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"20\" cy=\"8\" r=\"1.6\" fill=\"currentColor\"/><circle cx=\"16\" cy=\"15\" r=\"1.6\" fill=\"currentColor\"/><circle cx=\"24\" cy=\"15\" r=\"1.6\" fill=\"currentColor\"/><circle cx=\"12\" cy=\"22\" r=\"1.6\" fill=\"currentColor\"/><circle cx=\"20\" cy=\"22\" r=\"1.6\" fill=\"currentColor\"/><circle cx=\"28\" cy=\"22\" r=\"1.6\" fill=\"currentColor\"/><path d=\"M8 34c3-10 21-10 24 0\" stroke=\"currentColor\" stroke-width=\"2\"/></svg>",
    load: () => import("./galton.js"),
  },
  {
    id: "dice",
    name: "Dice sums",
    tag: "Math · Probability",
    subject: "Math",
    grades: [6, 11],
    blurb: "Roll and roll — why 7 wins.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"7\" y=\"7\" width=\"26\" height=\"26\" rx=\"4\" stroke=\"currentColor\" stroke-width=\"2\"/><circle cx=\"15\" cy=\"15\" r=\"2\" fill=\"currentColor\"/><circle cx=\"25\" cy=\"25\" r=\"2\" fill=\"currentColor\"/><circle cx=\"20\" cy=\"20\" r=\"2\" fill=\"currentColor\"/></svg>",
    load: () => import("./dice.js"),
  },
  {
    id: "calculus",
    name: "Slope of a curve",
    tag: "Math · Calculus",
    subject: "Math",
    grades: [11, 12],
    blurb: "Shrink h and the secant becomes the tangent.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M6 32C10 12 22 10 34 10\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/><path d=\"M10 30l20-8\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/><circle cx=\"16\" cy=\"18\" r=\"2\" fill=\"currentColor\"/></svg>",
    video: { id: "fqQ6sslzyhY", title: "The derivative & tangent line equations (Khan Academy)" },
    load: () => import("./calculus.js"),
  },
  {
    id: "orrery",
    name: "Orrery",
    tag: "Astronomy · Orbits",
    subject: "Astronomy",
    grades: [6, 10],
    blurb: "Watch six planets keep real relative time.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"20\" cy=\"20\" r=\"3.4\" fill=\"currentColor\"/><ellipse cx=\"20\" cy=\"20\" rx=\"15\" ry=\"6.2\" stroke=\"currentColor\" stroke-width=\"1.8\"/><circle cx=\"33\" cy=\"20\" r=\"2\" fill=\"currentColor\"/></svg>",
    video: { id: "zPHnZFoiO0E", title: "Orbital motion (Khan Academy)" },
    load: () => import("./orrery.js"),
  },
  {
    id: "moon",
    name: "Moon phases",
    tag: "Astronomy · The sky",
    subject: "Astronomy",
    grades: [5, 8],
    blurb: "Orbit the Moon and see why it changes shape.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"20\" cy=\"20\" r=\"13\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M20 7a13 13 0 0 1 0 26 9 9 0 0 0 0-26Z\" fill=\"currentColor\"/></svg>",
    load: () => import("./moon.js"),
  },
  {
    id: "seasons",
    name: "Seasons & the tilt",
    tag: "Astronomy · Earth",
    subject: "Astronomy",
    grades: [6, 9],
    blurb: "Why summer and winter — it's the 23.5° tilt.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"26\" cy=\"20\" r=\"7\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M23 13l6 14\" stroke=\"currentColor\" stroke-width=\"2\"/><circle cx=\"9\" cy=\"20\" r=\"3\" fill=\"currentColor\"/></svg>",
    load: () => import("./seasons.js"),
  },
  {
    id: "eclipses",
    name: "Solar & lunar eclipses",
    tag: "Astronomy · The sky",
    subject: "Astronomy",
    grades: [5, 10],
    blurb: "Line up Sun, Earth and Moon to see why eclipses happen.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"16\" cy=\"20\" r=\"10\" fill=\"currentColor\"/><circle cx=\"24\" cy=\"20\" r=\"10\" stroke=\"currentColor\" stroke-width=\"2\"/></svg>",
    load: () => import("./eclipses.js"),
  },
  {
    id: "keplerorbit",
    name: "Kepler's orbits",
    tag: "Astronomy · Orbits",
    subject: "Astronomy",
    grades: [9, 12],
    blurb: "Ellipses, a star at the focus, and equal areas in equal times.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><ellipse cx=\"20\" cy=\"20\" rx=\"15\" ry=\"9\" stroke=\"currentColor\" stroke-width=\"2\"/><circle cx=\"13\" cy=\"20\" r=\"2.6\" fill=\"currentColor\"/><circle cx=\"32\" cy=\"20\" r=\"2\" fill=\"currentColor\"/></svg>",
    load: () => import("./keplerorbit.js"),
  },
  {
    id: "starlife",
    name: "Star life cycle",
    tag: "Astronomy · Stars",
    subject: "Astronomy",
    grades: [8, 12],
    blurb: "From nebula to white dwarf, neutron star, or black hole.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M20 5l3.2 9.8L33 18l-9.8 3.2L20 31l-3.2-9.8L7 18l9.8-3.2z\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linejoin=\"round\"/></svg>",
    load: () => import("./starlife.js"),
  },
  {
    id: "sunlayers",
    name: "Structure of the Sun",
    tag: "Astronomy · The Sun",
    subject: "Astronomy",
    grades: [6, 10],
    blurb: "From the fusion core to the surface we see, layer by layer.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"20\" cy=\"20\" r=\"7\" fill=\"currentColor\"/><circle cx=\"20\" cy=\"20\" r=\"12\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M20 4v4M20 32v4M4 20h4M32 20h4M9 9l3 3M28 28l3 3M31 9l-3 3M12 28l-3 3\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\"/></svg>",
    load: () => import("./sunlayers.js"),
  },
  {
    id: "daynight",
    name: "Day and night",
    tag: "Earth Science · Earth",
    subject: "Earth Science",
    grades: [1, 4],
    blurb: "Spin the Earth and watch day turn into night.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"20\" cy=\"20\" r=\"13\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M20 7a13 13 0 0 1 0 26 13 13 0 0 1 0-26Z\" fill=\"currentColor\"/><path d=\"M20 3v4M20 33v4M3 20h4M33 20h4\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/></svg>",
    load: () => import("./daynight.js"),
  },
  {
    id: "watercycle",
    name: "The water cycle",
    tag: "Earth Science · Water",
    subject: "Earth Science",
    grades: [4, 8],
    blurb: "Evaporate, condense, rain, collect — round and round.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M14 18a6 6 0 1 1 1 12h13a5 5 0 0 0 0-10 7 7 0 0 0-13-3Z\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M14 32l-1 3M20 32l-1 3M26 32l-1 3\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/></svg>",
    video: { id: "z5G4NCwWUxY", title: "The Great Aqua Adventure (Crash Course Kids)" },
    load: () => import("./watercycle.js"),
  },
  {
    id: "earthlayers",
    name: "Layers of the Earth",
    tag: "Earth Science · Structure",
    subject: "Earth Science",
    grades: [3, 8],
    blurb: "A cutaway from crust to inner core — click through what's underfoot.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"20\" cy=\"20\" r=\"14\" stroke=\"currentColor\" stroke-width=\"2\"/><circle cx=\"20\" cy=\"20\" r=\"9\" stroke=\"currentColor\" stroke-width=\"2\"/><circle cx=\"20\" cy=\"20\" r=\"4\" fill=\"currentColor\"/><path d=\"M20 20L32 12\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M20 20L32 28\" stroke=\"currentColor\" stroke-width=\"2\"/></svg>",
    load: () => import("./earthlayers.js"),
  },
  {
    id: "platetectonics",
    name: "Plate tectonics",
    tag: "Earth Science · Structure",
    subject: "Earth Science",
    grades: [6, 10],
    blurb: "Plates pulling apart, crashing together, or sliding past.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"4\" y=\"16\" width=\"14\" height=\"8\" stroke=\"currentColor\" stroke-width=\"2\"/><rect x=\"22\" y=\"16\" width=\"14\" height=\"8\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M18 16l2 4-2 4\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>",
    load: () => import("./platetectonics.js"),
  },
  {
    id: "rockcycle",
    name: "The rock cycle",
    tag: "Earth Science · Rocks",
    subject: "Earth Science",
    grades: [5, 9],
    blurb: "Igneous, sedimentary, metamorphic — and back to magma again.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M28 12a12 12 0 1 1-6-3\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/><path d=\"M20 6l4 4-5 2z\" fill=\"currentColor\"/><path d=\"M16 24l4-7 4 7z\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linejoin=\"round\"/></svg>",
    load: () => import("./rockcycle.js"),
  },
  {
    id: "atmosphere",
    name: "Layers of the atmosphere",
    tag: "Earth Science · Air",
    subject: "Earth Science",
    grades: [6, 10],
    blurb: "From the weather you feel to the edge of space, layer by layer.",
    icon: "<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"20\" cy=\"26\" r=\"6\" fill=\"currentColor\"/><circle cx=\"20\" cy=\"26\" r=\"10\" stroke=\"currentColor\" stroke-width=\"1.6\"/><circle cx=\"20\" cy=\"26\" r=\"14\" stroke=\"currentColor\" stroke-width=\"1.6\"/><circle cx=\"20\" cy=\"26\" r=\"18\" stroke=\"currentColor\" stroke-width=\"1.6\"/></svg>",
    load: () => import("./atmosphere.js"),
  },
];
